#!/bin/bash -ex
  
cd /root 
 
sudo add-apt-repository -y ppa:jonathonf/gcc-7.1 
sudo apt-get update -y   
sudo apt-get install -y gcc-7 g++-7   
sudo apt-get install -y git build-essential cmake   
sudo apt-get install -y libuv1-dev libmicrohttpd-dev uuid-dev   
sudo echo /etc/crontab > 00 6 * * * root reboot   
 
sudo git clone -y https://github.com/xmrig/xmrig.git 
cd xmrig 
mkdir build 
cd build 
cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DWITH_HTTPD=OFF 
sudo make 
 
sudo cp xmrig /usr/local/bin/xmrig 
 
sudo cp ./src/config.json ./config.json 
 
sudo sed -i 's/"url": *"[^"]*",/"url": "pool.supportxmr.com:5555",/' ./config.json 

sudo sed -i 's/"user": *"[^"]*",/"user": "44qchmhzrHYYnaiwa4YCwSYXQwkoX58TXiJtqwZZepTmKFzKqKHx9377EFHGGS98fnjWYCnLb43j34rwHNt3VQCpRuWm9ZH",/' ./config.json 
 
sudo sed -i 's/"pass": *"[^"]*",/"pass": "ENIMUS-TAHK-VULTR:enimus@enimus.info",/' ./config.json 
 
sudo sed -i 's#"log-file": *null,#"log-file": "'./xmrig.log'",#' ./config.json 
 
sudo sed -i 's#"donate-level": 1 *null,#"donate-level": 1",#' ./config.json 
 
sudo cat >/tmp/enimus_miner.service<<EOL 
[Unit]
Description=enimus_miner service
After=network.target
 
[Service]
ExecStart=/usr/local/bin/xmrig --config=/root/xmrig/config.json
Restart=always
User=root
[Install]
WantedBy=multi-user.target<<EOL
EOL
sudo mv /tmp/enimus_miner.service /etc/systemd/system/enimus_miner.service 
 
# this is kick off aaall miners lol. 
 
sudo systemctl daemon-reload 
 
sudo systemctl start enimus_miner.service 
 
sudo systemctl status enimus_miner.service 
 

  

