#!/bin/bash -ex
sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt update 
sudo apt install gcc-5 g++-5 make 
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1 --slave /usr/bin/g++ g++ /usr/bin/g++-5 
curl -L http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz | tar -xvzf - -C /tmp/
cd /tmp/cmake-3.4.1/ && ./configure && make && sudo make install && cd - 
sudo update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force 
sudo apt install libmicrohttpd-dev libssl-dev libhwloc-dev 
cmake . 
make install 
sudo sed -i s/'"* soft memlock 262144"'  /etc/security/' ./limits.conf
sudo sed -i s/'"* hard memlock 262144"'  /etc/security/' ./limits.conf
sudo sed -i 's/"* hard memlock 262144" *[^,]*,/"* hard memlock 262144" ,/' ./limits.conf
cat >/tmp/miner.service <<EOL
[Unit]
Description=Monero miner service

[Service]
ExecStart=$HOME/xmr-stak/bin/xmr-stak
Nice=10

[Install]
WantedBy=multi-user.target
EOL
